#!/usr/bin/env Rscript
# ==============================================================================
# Stromal SMC / Pericyte Tissue Comparison Pipeline v1.0.0
# ==============================================================================
#
# Purpose:
#   Reuse the validated shared tissue-comparison backbone from the B-cell v2.6
#   workflow, but point it at the branch-specific stromal SMC/pericyte reference
#   generated by `stromal_reintegration_branchwise_scvi_scanvi_20260407_v1_5.py`.
#
# Scope:
#   - input: branch-specific SMC/pericyte reference h5ad
#   - L3: branch-specific scANVI prediction (`cell_type_scanvi_pred`)
#   - L2: keep existing coarse annotation (`cell_type_L2`)
#   - downstream: visualization / pseudobulk DE / enrichment / ssGSEA / CHOIR / LLM
#
# Smoke test:
#   PIPELINE_TEST_MODE=true Rscript stromal_smc_tissue_comparison_20260408_v1_0.R
#
# Date: 2026-04-08
# ==============================================================================

LINEAGE_TAG           <- "STROMAL_SMC"
LINEAGE_DISPLAY       <- "Stromal SMC/Pericyte"
LINEAGE_CONTEXT_LABEL <- "smooth muscle cells and pericytes"
LINEAGE_CONTEXT_LOWER <- "stromal-smc-pericyte"
BIOLOGICAL_QUESTION_FRAGMENT <- paste(
  "vascular tone, mural-cell specialization, pulmonary-versus-systemic pericyte programs,",
  "contractility, perivascular immune recruitment, or tissue microenvironment"
)

PIPELINE_VERSION_LABEL <- "v1.0.0-SMC"
PIPELINE_SUBTITLE <- paste(
  "Stromal SMC/Pericyte Tissue Comparison v1.0.0",
  "(branch-specific scANVI reference, pseudobulk DESeq2, enrichment, ssGSEA, CHOIR)"
)
REPORT_TITLE <- "# Stromal SMC / Pericyte Tissue Comparison Report (Normal Respiratory Tract)"
GENERATED_BY_LABEL <- "stromal_smc_tissue_comparison_20260408_v1_0.R"
FINAL_FILE_PREFIX  <- "stromal_smc_tissue_comparison_final"
LINEAGE_COMPLETION_BANNER <- "STROMAL SMC/PERICYTE TISSUE COMPARISON COMPLETE (v1.0.0-SMC)"

H5AD_PATH  <- "/home/h2048/data/py/0407/stromal_reintegration_v1_5_branchwise/smc/adata_smc_reference_v1_5_branchwise.h5ad"
OUTPUT_DIR <- "/home/h2048/data/R/0408/stromal_smc_tissue_comparison_v1_0"

USE_EXISTING_L2 <- TRUE
L2_SOURCE_COL   <- "cell_type_L2"
L3_SOURCE_COL   <- "cell_type_scanvi_pred"
ANALYSIS_L3_DESCRIPTION <- "branch-specific SMC/pericyte scANVI predictions"
L3_TO_L2_TABLE_HEADER_LEFT <- sprintf("L3 (`%s`)", L3_SOURCE_COL)

UMAP_REDUCTION_PREFERRED <- c("umap", "umap_scanvi", "umap_scvi")
CHOIR_REDUCTION_CANDIDATES <- c("scanvi", "scvi", "pca")
CHOIR_ALPHA <- 0.20
CHOIR_VAR_FEATURES_MAX <- 4000L

CUSTOM_DB_NAME  <- "Stromal_SMC_custom"
CUSTOM_DB_LABEL <- "stromal SMC/pericyte custom markers"
CUSTOM_ENRICHMENT_SIZE_RULE <- c(min = 2L, max = 120L)
CELLMARKER_CELLTYPE_PATTERN <- paste(
  "Smooth muscle|vascular smooth muscle|pericyte|mural cell|perivascular|",
  "vascular mural|perivascular smooth muscle"
)
PANGLAODB_CELLTYPE_PATTERN <- paste(
  "Smooth muscle|vascular smooth muscle|pericyte|mural cell|perivascular"
)

KNOWN_MARKERS <- unique(c(
  "RGS5", "PDGFRB", "CSPG4", "MCAM", "ABCC9", "KCNJ8", "NOTCH3",
  "ACTA2", "TAGLN", "MYH11", "CNN1", "MYLK", "PRKG1", "CALD1", "DES",
  "CXCL12", "CCL2", "SEMA3G", "CASQ2",
  "SOX10", "S100B",
  "PTPRC", "LST1"
))

CUSTOM_MARKERS_DB <- data.frame(
  subtype = c(
    "Muscle_pericyte_pulmonary",
    "Muscle_pericyte_systemic",
    "Muscle_perivascular_immune_recruiting",
    "Muscle_smooth_pulmonary",
    "Muscle_smooth_arterial_systemic"
  ),
  markers = c(
    "RGS5,PDGFRB,CSPG4,MCAM,KCNJ8,ABCC9",
    "RGS5,PDGFRB,NOTCH3,MCAM,DES,CSPG4",
    "RGS5,PDGFRB,CXCL12,CCL2,SEMA3G,NOTCH3",
    "ACTA2,TAGLN,MYH11,CNN1,MYLK,PRKG1",
    "ACTA2,MYH11,TAGLN,CALD1,CNN1,MYLK"
  ),
  stringsAsFactors = FALSE
)

LINEAGE_BASE_CONTEXT <- paste(
  "Smooth muscle cells and pericytes from NORMAL (non-diseased) human respiratory tract tissues.",
  "This is a cross-site anatomical comparison, NOT a disease-vs-healthy comparison.",
  "Key mural-cell programs include vascular tone control, contractility, vessel stabilization,",
  "pericyte support, and perivascular immune recruitment.",
  "Focus: regional variation in pulmonary versus systemic mural-cell programs across respiratory tissues."
)

TISSUE_CONTEXT <- list(
  "nose" = paste(
    "Nasal mucosa: mural cells support vascular reactivity, microvascular stability,",
    "and rapid regulation of leukocyte entry in an exposure-heavy environment."
  ),
  "sinus" = paste(
    "Paranasal sinus: mural-cell programs may reflect drainage-linked vascular tone,",
    "low-flow vessel maintenance, and perivascular immune positioning."
  ),
  "respiratory airway" = paste(
    "Conducting airway: smooth muscle and pericytes contribute to airway-adjacent vessel behavior,",
    "bronchovascular niche support, and contractile / inflammatory crosstalk."
  ),
  "lung parenchyma" = paste(
    "Lung parenchyma: mural-cell specialization is linked to pulmonary circulation,",
    "alveolar microvascular stability, and local control of perfusion and immune trafficking."
  )
)

PIPELINE_CHANGELOG_TITLE <- sprintf("%s Changes:", PIPELINE_VERSION_LABEL)
PIPELINE_CHANGELOG_LINES <- c(
  "  [SMC-1] Uses the branchwise stromal SMC/pericyte reference from 2026-04-07 as input.",
  "  [SMC-2] Keeps existing L2 and sets L3 to `cell_type_scanvi_pred` for branch-specific mural-cell analysis.",
  "  [SMC-3] Adds SMC/pericyte-focused marker panels and a custom subtype marker database.",
  "  [SMC-4] Keeps CHOIR alpha at 0.20 to reduce over-fragmentation in the shared engine.",
  "  [SMC-5] Reuses the validated shared tissue-comparison engine instead of duplicating downstream logic."
)
PIPELINE_INHERITED_FIXES_TITLE <- "Shared engine fixes inherited from the validated template:"
PIPELINE_INHERITED_FIX_LINES <- c(
  "  [ENGINE-1] Sparse-friendly pseudobulk aggregation with one-shot cache per level.",
  "  [ENGINE-2] interpret_agent retry + normalization to fixed JSON schema.",
  "  [ENGINE-3] ssGSEA grouped LLM outputs are aggregated at tissue x group resolution.",
  "  [ENGINE-4] CHOIR/OFA downstream outputs are exported with structured tables and reports.",
  "  [ENGINE-5] H5AD export preserves layers/raw and sanitizes object columns for write safety."
)

source("/home/h2048/script/R/bcell_tissue_comparison_v2_6_20260406.R")