#!/usr/bin/env Rscript
# ==============================================================================
# Stromal Endothelial Tissue Comparison Pipeline v1.0.0
# ==============================================================================
#
# Purpose:
#   Reuse the validated shared tissue-comparison backbone from the B-cell v2.6
#   workflow, but point it at the branch-specific stromal endothelial reference
#   generated by `stromal_reintegration_branchwise_scvi_scanvi_20260407_v1_5.py`.
#
# Scope:
#   - input: branch-specific endothelial reference h5ad
#   - L3: branch-specific scANVI prediction (`cell_type_scanvi_pred`)
#   - L2: keep existing coarse annotation (`cell_type_L2`)
#   - downstream: visualization / pseudobulk DE / enrichment / ssGSEA / CHOIR / LLM
#
# Smoke test:
#   PIPELINE_TEST_MODE=true Rscript stromal_endothelial_tissue_comparison_20260408_v1_0.R
#
# Date: 2026-04-08
# ==============================================================================

LINEAGE_TAG           <- "STROMAL_ENDOTHELIAL"
LINEAGE_DISPLAY       <- "Stromal Endothelial"
LINEAGE_CONTEXT_LABEL <- "stromal endothelial cells"
LINEAGE_CONTEXT_LOWER <- "stromal-endothelial"
BIOLOGICAL_QUESTION_FRAGMENT <- paste(
  "vascular zonation, lymphatic drainage, capillary specialization, arterial-versus-venous programs,",
  "barrier adaptation, endothelial activation, or tissue microenvironment"
)

PIPELINE_VERSION_LABEL <- "v1.0.0-Endothelial"
PIPELINE_SUBTITLE <- paste(
  "Stromal Endothelial Tissue Comparison v1.0.0",
  "(branch-specific scANVI reference, pseudobulk DESeq2, enrichment, ssGSEA, CHOIR)"
)
REPORT_TITLE <- "# Stromal Endothelial Tissue Comparison Report (Normal Respiratory Tract)"
GENERATED_BY_LABEL <- "stromal_endothelial_tissue_comparison_20260408_v1_0.R"
FINAL_FILE_PREFIX  <- "stromal_endothelial_tissue_comparison_final"
LINEAGE_COMPLETION_BANNER <- "STROMAL ENDOTHELIAL TISSUE COMPARISON COMPLETE (v1.0.0-Endothelial)"

H5AD_PATH  <- "/home/h2048/data/py/0407/stromal_reintegration_v1_5_branchwise/endothelial/adata_endothelial_reference_v1_5_branchwise.h5ad"
OUTPUT_DIR <- "/home/h2048/data/R/0408/stromal_endothelial_tissue_comparison_v1_0"

USE_EXISTING_L2 <- TRUE
L2_SOURCE_COL   <- "cell_type_L2"
L3_SOURCE_COL   <- "cell_type_scanvi_pred"
ANALYSIS_L3_DESCRIPTION <- "branch-specific endothelial scANVI predictions"
L3_TO_L2_TABLE_HEADER_LEFT <- sprintf("L3 (`%s`)", L3_SOURCE_COL)

UMAP_REDUCTION_PREFERRED <- c("umap", "umap_scanvi", "umap_scvi")
CHOIR_REDUCTION_CANDIDATES <- c("scanvi", "scvi", "pca")
CHOIR_ALPHA <- 0.20
CHOIR_VAR_FEATURES_MAX <- 4000L

CUSTOM_DB_NAME  <- "Stromal_Endothelial_custom"
CUSTOM_DB_LABEL <- "stromal endothelial custom markers"
CUSTOM_ENRICHMENT_SIZE_RULE <- c(min = 2L, max = 120L)
CELLMARKER_CELLTYPE_PATTERN <- paste(
  "Endothelial|Endothelia|vascular endothelial|capillary endothelial|arterial endothelial|",
  "venous endothelial|lymphatic endothelial|microvascular endothelial"
)
PANGLAODB_CELLTYPE_PATTERN <- paste(
  "Endothelial|vascular endothelial|capillary endothelial|arterial endothelial|",
  "venous endothelial|lymphatic endothelial"
)

KNOWN_MARKERS <- unique(c(
  "PECAM1", "CDH5", "VWF", "KDR", "CLDN5", "EMCN",
  "PROX1", "PDPN", "LYVE1", "CCL21", "FLT4", "MMRN1",
  "CA4", "EDNRB", "RGCC", "GPIHBP1", "BTNL9", "AQP1",
  "GJA5", "EFNB2", "SOX17", "SEMA3G", "BMX",
  "ACKR1", "SELE", "SELP", "VCAM1", "CXCL12", "CXCR4",
  "ISG15", "IFIT1", "IFIT3", "STAT1",
  "PTPRC", "LST1"
))

CUSTOM_MARKERS_DB <- data.frame(
  subtype = c(
    "Endothelia_Lymphatic",
    "Endothelia_vascular_Cap_a",
    "Endothelia_vascular_Cap_g",
    "Endothelia_vascular_arterial_pulmonary",
    "Endothelia_vascular_arterial_systemic",
    "Endothelia_vascular_venous_pulmonary",
    "Endothelia_vascular_venous_systemic"
  ),
  markers = c(
    "PROX1,PDPN,LYVE1,CCL21,FLT4,MMRN1",
    "CA4,EDNRB,RGCC,GPIHBP1,CD36,AQP1",
    "KDR,EMCN,BTNL9,ADGRL4,EPAS1,PLVAP",
    "GJA5,EFNB2,SOX17,CXCL12,KCNJ8,FBLN5",
    "GJA5,EFNB2,SEMA3G,BMX,HEY1,SOX17",
    "ACKR1,SELP,VWF,NR2F2,PLVAP,EMCN",
    "ACKR1,SELE,VWF,VCAM1,CXCR4,ISG15"
  ),
  stringsAsFactors = FALSE
)

LINEAGE_BASE_CONTEXT <- paste(
  "Stromal endothelial cells from NORMAL (non-diseased) human respiratory tract tissues.",
  "This is a cross-site anatomical comparison, NOT a disease-vs-healthy comparison.",
  "Key endothelial programs include lymphatic drainage, capillary specialization, arterial/venous zonation,",
  "vascular barrier maintenance, leukocyte trafficking, and inflammatory activation states.",
  "Focus: regional variation in endothelial specialization along nose, sinus, conducting airway, and lung parenchyma."
)

TISSUE_CONTEXT <- list(
  "nose" = paste(
    "Nasal mucosa: first-line vascular interface under intense environmental exposure,",
    "with active leukocyte trafficking, vascular barrier tuning, and lymphatic drainage."
  ),
  "sinus" = paste(
    "Paranasal sinus: semi-enclosed mucosal compartment where endothelial programs may reflect drainage,",
    "fluid handling, and low-flow barrier surveillance."
  ),
  "respiratory airway" = paste(
    "Conducting airway: endothelial cells support mucosal immune cell recruitment, epithelial-stromal crosstalk,",
    "and vessel adaptation near bronchi and glands."
  ),
  "lung parenchyma" = paste(
    "Lung parenchyma: endothelial specialization is tightly linked to alveolar gas exchange,",
    "capillary zonation, vascular permeability control, and pulmonary circulation biology."
  )
)

PIPELINE_CHANGELOG_TITLE <- sprintf("%s Changes:", PIPELINE_VERSION_LABEL)
PIPELINE_CHANGELOG_LINES <- c(
  "  [ENDO-1] Uses the branchwise stromal endothelial reference from 2026-04-07 as input.",
  "  [ENDO-2] Keeps existing L2 and sets L3 to `cell_type_scanvi_pred` for branch-specific endothelial analysis.",
  "  [ENDO-3] Adds endothelial-focused marker panels and a custom subtype marker database.",
  "  [ENDO-4] Keeps CHOIR alpha at 0.20 to reduce over-fragmentation in the shared engine.",
  "  [ENDO-5] Reuses the validated shared tissue-comparison engine instead of duplicating downstream logic."
)
PIPELINE_INHERITED_FIXES_TITLE <- "Shared engine fixes inherited from the validated template:"
PIPELINE_INHERITED_FIX_LINES <- c(
  "  [ENGINE-1] Sparse-friendly pseudobulk aggregation with one-shot cache per level.",
  "  [ENGINE-2] interpret_agent retry + normalization to fixed JSON schema.",
  "  [ENGINE-3] ssGSEA grouped LLM outputs are aggregated at tissue x group resolution.",
  "  [ENGINE-4] CHOIR/OFA downstream outputs are exported with structured tables and reports.",
  "  [ENGINE-5] H5AD export preserves layers/raw and sanitizes object columns for write safety."
)

source("/home/h2048/script/R/bcell_tissue_comparison_v2_6_20260406.R")