#!/usr/bin/env Rscript
# ==============================================================================
# Stromal Fibroblast Tissue Comparison Pipeline v1.0.0
# ==============================================================================
#
# Purpose:
#   Reuse the validated shared tissue-comparison backbone from the B-cell v2.6
#   workflow, but point it at the branch-specific stromal fibroblast reference
#   generated by `stromal_reintegration_branchwise_scvi_scanvi_20260407_v1_5.py`.
#
# Scope:
#   - input: branch-specific fibroblast reference h5ad
#   - L3: branch-specific scANVI prediction (`cell_type_scanvi_pred`)
#   - L2: keep existing coarse annotation (`cell_type_L2`)
#   - downstream: visualization / pseudobulk DE / enrichment / ssGSEA / CHOIR / LLM
#
# Smoke test:
#   PIPELINE_TEST_MODE=true Rscript stromal_fibroblast_tissue_comparison_20260408_v1_0.R
#
# Date: 2026-04-08
# ==============================================================================

LINEAGE_TAG           <- "STROMAL_FIBROBLAST"
LINEAGE_DISPLAY       <- "Stromal Fibroblast"
LINEAGE_CONTEXT_LABEL <- "stromal fibroblasts"
LINEAGE_CONTEXT_LOWER <- "stromal-fibroblast"
BIOLOGICAL_QUESTION_FRAGMENT <- paste(
  "ECM remodeling, niche support, adventitial-versus-alveolar specialization,",
  "peribronchial support programs, stress activation, wound-response, or tissue microenvironment"
)

PIPELINE_VERSION_LABEL <- "v1.0.0-Fibroblast"
PIPELINE_SUBTITLE <- paste(
  "Stromal Fibroblast Tissue Comparison v1.0.0",
  "(branch-specific scANVI reference, pseudobulk DESeq2, enrichment, ssGSEA, CHOIR)"
)
REPORT_TITLE <- "# Stromal Fibroblast Tissue Comparison Report (Normal Respiratory Tract)"
GENERATED_BY_LABEL <- "stromal_fibroblast_tissue_comparison_20260408_v1_0.R"
FINAL_FILE_PREFIX  <- "stromal_fibroblast_tissue_comparison_final"
LINEAGE_COMPLETION_BANNER <- "STROMAL FIBROBLAST TISSUE COMPARISON COMPLETE (v1.0.0-Fibroblast)"

H5AD_PATH  <- "/home/h2048/data/py/0407/stromal_reintegration_v1_5_branchwise/fibroblast/adata_fibroblast_reference_v1_5_branchwise.h5ad"
OUTPUT_DIR <- "/home/h2048/data/R/0408/stromal_fibroblast_tissue_comparison_v1_0"

USE_EXISTING_L2 <- TRUE
L2_SOURCE_COL   <- "cell_type_L2"
L3_SOURCE_COL   <- "cell_type_scanvi_pred"
ANALYSIS_L3_DESCRIPTION <- "branch-specific fibroblast scANVI predictions"
L3_TO_L2_TABLE_HEADER_LEFT <- sprintf("L3 (`%s`)", L3_SOURCE_COL)

UMAP_REDUCTION_PREFERRED <- c("umap", "umap_scanvi", "umap_scvi")
CHOIR_REDUCTION_CANDIDATES <- c("scanvi", "scvi", "pca")
CHOIR_ALPHA <- 0.20
CHOIR_VAR_FEATURES_MAX <- 4000L

CUSTOM_DB_NAME  <- "Stromal_Fibroblast_custom"
CUSTOM_DB_LABEL <- "stromal fibroblast custom markers"
CUSTOM_ENRICHMENT_SIZE_RULE <- c(min = 2L, max = 120L)
CELLMARKER_CELLTYPE_PATTERN <- paste(
  "Fibroblast|stromal fibroblast|adventitial fibroblast|alveolar fibroblast|",
  "peribronchial fibroblast|myofibroblast|mesenchymal stromal"
)
PANGLAODB_CELLTYPE_PATTERN <- paste(
  "Fibroblast|stromal fibroblast|adventitial fibroblast|alveolar fibroblast|",
  "peribronchial fibroblast|myofibroblast"
)

KNOWN_MARKERS <- unique(c(
  "DCN", "LUM", "COL1A1", "COL1A2", "COL3A1", "MFAP4", "PDGFRA",
  "PI16", "MFAP5", "CD34", "TCF21", "C7", "DPT",
  "POSTN", "CTHRC1", "FN1", "ACTA2", "TAGLN", "COL11A1",
  "APOE", "FABP4", "INMT", "CFD", "CXCL14",
  "ISG15", "IFIT1", "IFIT3", "CXCL10", "STAT1", "BST2",
  "PTPRC", "MS4A1"
))

CUSTOM_MARKERS_DB <- data.frame(
  subtype = c(
    "Fibro_adventitial",
    "Fibro_peribronchial",
    "Fibro_alveolar",
    "Fibro_stress_activated",
    "Fibro_myofibroblast"
  ),
  markers = c(
    "PI16,MFAP5,CD34,C7,DPT,TCF21",
    "COL1A1,COL1A2,COL3A1,LUM,DCN,MFAP4",
    "APOE,FABP4,INMT,NPNT,CFD,CXCL14",
    "ISG15,IFIT1,IFIT3,CXCL10,STAT1,BST2",
    "POSTN,CTHRC1,ACTA2,TAGLN,COL11A1,FN1"
  ),
  stringsAsFactors = FALSE
)

LINEAGE_BASE_CONTEXT <- paste(
  "Stromal fibroblasts from NORMAL (non-diseased) human respiratory tract tissues.",
  "This is a cross-site anatomical comparison, NOT a disease-vs-healthy comparison.",
  "Key fibroblast programs include ECM deposition, matrix remodeling, airway wall support,",
  "adventitial niche formation, alveolar stromal support, and stress / repair activation.",
  "Focus: regional variation in fibroblast specialization across upper airway, conducting airway, and parenchyma."
)

TISSUE_CONTEXT <- list(
  "nose" = paste(
    "Nasal mucosa: fibroblasts contribute to barrier support, lamina propria structure,",
    "and rapid remodeling under constant environmental exposure."
  ),
  "sinus" = paste(
    "Paranasal sinus: fibroblast programs may reflect matrix maintenance in a semi-enclosed cavity,",
    "with drainage-dependent remodeling and stromal support."
  ),
  "respiratory airway" = paste(
    "Conducting airway: fibroblasts support peribronchial ECM, airway wall mechanics, gland-associated stroma,",
    "and epithelial-stromal signaling."
  ),
  "lung parenchyma" = paste(
    "Lung parenchyma: fibroblasts support alveolar architecture, interstitial matrix balance,",
    "and niche signaling tied to gas-exchange tissue homeostasis."
  )
)

PIPELINE_CHANGELOG_TITLE <- sprintf("%s Changes:", PIPELINE_VERSION_LABEL)
PIPELINE_CHANGELOG_LINES <- c(
  "  [FIB-1] Uses the branchwise stromal fibroblast reference from 2026-04-07 as input.",
  "  [FIB-2] Keeps existing L2 and sets L3 to `cell_type_scanvi_pred` for branch-specific fibroblast analysis.",
  "  [FIB-3] Adds fibroblast-focused marker panels and a custom subtype marker database.",
  "  [FIB-4] Keeps CHOIR alpha at 0.20 to reduce over-fragmentation in the shared engine.",
  "  [FIB-5] Reuses the validated shared tissue-comparison engine instead of duplicating downstream logic."
)
PIPELINE_INHERITED_FIXES_TITLE <- "Shared engine fixes inherited from the validated template:"
PIPELINE_INHERITED_FIX_LINES <- c(
  "  [ENGINE-1] Sparse-friendly pseudobulk aggregation with one-shot cache per level.",
  "  [ENGINE-2] interpret_agent retry + normalization to fixed JSON schema.",
  "  [ENGINE-3] ssGSEA grouped LLM outputs are aggregated at tissue x group resolution.",
  "  [ENGINE-4] CHOIR/OFA downstream outputs are exported with structured tables and reports.",
  "  [ENGINE-5] H5AD export preserves layers/raw and sanitizes object columns for write safety."
)

source("/home/h2048/script/R/bcell_tissue_comparison_v2_6_20260406.R")