#!/usr/bin/env Rscript
# ==============================================================================
# T/NK Tissue Comparison Pipeline v2.6.2-TNK-rmCHOIR
# ==============================================================================
#
# Purpose:
#   - rerun the TNK tissue-comparison pipeline after removing selected CHOIR
#     clusters from the previous run and retraining scVI/scANVI using the
#     existing refined labels as supervision.
#   - keep the wrapper thin by reusing the generic wrapper interface.
#
# Upstream input generated by:
#   /home/h2048/script/py/tnk_scvi_scanvi_refined_rerun_rm_choir_20260413_v1.py
#
# Date: 2026-04-13
# ==============================================================================

GENERIC_WRAPPER_PATH <- "/home/h2048/script/R/tissue_comparison_generic_wrapper_20260412.R"
source(GENERIC_WRAPPER_PATH)

PIPELINE_CONFIG <- tc_build_generic_tissue_comparison_config(
  lineage = "TNK",
  overrides = list(
    REUSE_PREVIOUS_FINAL_OBJECT = FALSE,
    PIPELINE_VERSION_LABEL = "v2.6.2-TNK-rmCHOIR",
    PIPELINE_SUBTITLE = paste(
      "T/NK Tissue Comparison v2.6.2-TNK",
      "(remove selected CHOIR clusters + refined-label scVI/scANVI rerun)"
    ),
    GENERATED_BY_LABEL = "tnk_tissue_comparison_v2_6_2_20260413_rm_choir.R",
    LINEAGE_COMPLETION_BANNER = "T/NK TISSUE COMPARISON COMPLETE (v2.6.2-TNK-rmCHOIR)",
    H5AD_PATH = paste0(
      "/home/h2048/data/py/0413/tnk_scvi_scanvi_refined_rerun_rm_choir_20260413/",
      "adata_tnk_scanvi_refined_rerun_rm_choir_20260413.h5ad"
    ),
    OUTPUT_DIR = "/home/h2048/data/R/0413/tnk_tissue_comparison_v2_6_2_20260413_rm_choir",
    PREVIOUS_OUTPUT_DIR = "/home/h2048/data/R/0413/tnk_tissue_comparison_v2_6_1_20260413",
    PIPELINE_CHANGELOG_LINES = c(
      "  [RERUN-1] Removes user-selected CHOIR clusters c2/c10/c17/c20/c22/c29/c47 from the prior TNK run before upstream retraining.",
      "  [RERUN-2] Upstream scVI/scANVI is retrained from scratch on the filtered object while preserving the previous `scanvi_label_refined` supervision labels.",
      "  [RERUN-3] This wrapper consumes the freshly retrained refined-label H5AD instead of the original 0318 reference.",
      "  [RERUN-4] Previous 0413 TNK tissue-comparison output remains intact and is used as the previous-run baseline for preflight summary."
    )
  )
)

tc_run_generic_tissue_comparison(PIPELINE_CONFIG)
